In [1]:
import numpy as np  
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [2]:
print(type(my_array))

<class 'numpy.ndarray'>


In [3]:
np.random.random((3, 2))

array([[0.25854849, 0.52032972],
       [0.047961  , 0.84857852],
       [0.20503296, 0.99939702]])

In [4]:
import numpy as np  
my_array = np.array([1, 2, 3, 4, 5])
numbr = 18

new_array = my_array + numbr
print(new_array)

[19 20 21 22 23]


In [5]:
import numpy as np  
my_array = np.array([1, 2, 3, 4, 5])
your_array = np.array([6, 7, 8, 9, 10])
result_array = my_array + your_array
print(result_array)

[ 7  9 11 13 15]
